version: "3.9"
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: "rssdb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
